const productos = [
  {
    "idProducto": "hom-rem-001",
    "nombre": "Chomba Polo Club",
    "genero": "hombre",
    "categoria": "remera",
    "talle": "s",
    "estado": "usado en excelente estado",
    "precio": 18000,
    "stock": 1,
    "imagen": "assets/hombre-remera-1.jpg",
    "descripcion": "Chomba clásica a rayas.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-rem-002",
    "nombre": "Chomba Dolce & Gabbana",
    "genero": "hombre",
    "categoria": "remera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 21200,
    "stock": 2,
    "imagen": "assets/hombre-remera-2.jpg",
    "descripcion": "Chomba rayada 100% algodón",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-rem-003",
    "nombre": "Remera Converse 90'2",
    "genero": "hombre",
    "categoria": "remera",
    "talle": "l",
    "estado": "usado con detalles mínimos",
    "precio": 24400,
    "stock": 1,
    "imagen": "assets/hombre-remera-5.jpg",
    "descripcion": "remera faded negra seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-rem-004",
    "nombre": "Levis cat",
    "genero": "hombre",
    "categoria": "remera",
    "talle": "xl",
    "estado": "restaurado",
    "precio": 27600,
    "stock": 1,
    "imagen": "assets/hombre-remera-6.jpg",
    "descripcion": "Remera Levis 95's. 100% algodón.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-rem-005",
    "nombre": "Adidas 87's - Top edition",
    "genero": "hombre",
    "categoria": "remera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 30800,
    "stock": 2,
    "imagen": "assets/hombre-remera-4.jpg",
    "descripcion": "Remera Adidas clasica, 100% algodón",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-swe-001",
    "nombre": "Sweater Polo",
    "genero": "hombre",
    "categoria": "sweater",
    "talle": "m",
    "estado": "usado en excelente estado",
    "precio": 38000,
    "stock": 1,
    "imagen": "assets/hombre-sweater-1.jpg",
    "descripcion": "Sweater clásico Polo.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-swe-002",
    "nombre": "Sweater Levis",
    "genero": "hombre",
    "categoria": "sweater",
    "talle": "l",
    "estado": "usado en buen estado",
    "precio": 41200,
    "stock": 2,
    "imagen": "assets/hombre-sweater-2.jpg",
    "descripcion": "sweater cricket crema seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-swe-003",
    "nombre": "Sweater 95's Polo Ralph Lauren",
    "genero": "hombre",
    "categoria": "sweater",
    "talle": "s",
    "estado": "usado con detalles mínimos",
    "precio": 44400,
    "stock": 1,
    "imagen": "assets/hombre-sweater-3.jpg",
    "descripcion": "Sweater Polo Ralph Lauren. 100% lana.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-swe-004",
    "nombre": "cardigan vintage arena",
    "genero": "hombre",
    "categoria": "sweater",
    "talle": "m",
    "estado": "restaurado",
    "precio": 47600,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "cardigan vintage arena seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-swe-005",
    "nombre": "sweater cuello alto gris",
    "genero": "hombre",
    "categoria": "sweater",
    "talle": "xl",
    "estado": "usado en buen estado",
    "precio": 50800,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "sweater cuello alto gris seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-cam-001",
    "nombre": "campera denim gastada",
    "genero": "hombre",
    "categoria": "campera",
    "talle": "m",
    "estado": "usado en excelente estado",
    "precio": 69000,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera denim gastada seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-cam-002",
    "nombre": "campera cuero marrón",
    "genero": "hombre",
    "categoria": "campera",
    "talle": "l",
    "estado": "usado en buen estado",
    "precio": 72200,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera cuero marrón seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-cam-003",
    "nombre": "campera bomber retro",
    "genero": "hombre",
    "categoria": "campera",
    "talle": "s",
    "estado": "usado con detalles mínimos",
    "precio": 75400,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera bomber retro seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-cam-004",
    "nombre": "campera gabardina clásica",
    "genero": "hombre",
    "categoria": "campera",
    "talle": "xl",
    "estado": "restaurado",
    "precio": 78600,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera gabardina clásica seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-cam-005",
    "nombre": "campera varsity azul",
    "genero": "hombre",
    "categoria": "campera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 81800,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera varsity azul seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-pan-001",
    "nombre": "jean recto stone wash",
    "genero": "hombre",
    "categoria": "pantalon",
    "talle": "40",
    "estado": "usado en excelente estado",
    "precio": 46000,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "jean recto stone wash seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-pan-002",
    "nombre": "pantalón pinzado cacao",
    "genero": "hombre",
    "categoria": "pantalon",
    "talle": "42",
    "estado": "usado en buen estado",
    "precio": 49200,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "pantalón pinzado cacao seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-pan-003",
    "nombre": "pantalón cargo vintage",
    "genero": "hombre",
    "categoria": "pantalon",
    "talle": "44",
    "estado": "usado con detalles mínimos",
    "precio": 52400,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "pantalón cargo vintage seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-pan-004",
    "nombre": "jean negro relaxed",
    "genero": "hombre",
    "categoria": "pantalon",
    "talle": "38",
    "estado": "restaurado",
    "precio": 55600,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "jean negro relaxed seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-pan-005",
    "nombre": "pantalón pana marrón",
    "genero": "hombre",
    "categoria": "pantalon",
    "talle": "46",
    "estado": "usado en buen estado",
    "precio": 58800,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "pantalón pana marrón seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zat-001",
    "nombre": "zapatillas running noventas",
    "genero": "hombre",
    "categoria": "zapatilla",
    "talle": "39",
    "estado": "usado en excelente estado",
    "precio": 52000,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas running noventas seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zat-002",
    "nombre": "zapatillas lona crema",
    "genero": "hombre",
    "categoria": "zapatilla",
    "talle": "40",
    "estado": "usado en buen estado",
    "precio": 55200,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas lona crema seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zat-003",
    "nombre": "zapatillas retro azul",
    "genero": "hombre",
    "categoria": "zapatilla",
    "talle": "41",
    "estado": "usado con detalles mínimos",
    "precio": 58400,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas retro azul seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zat-004",
    "nombre": "zapatillas urbanas gastadas",
    "genero": "hombre",
    "categoria": "zapatilla",
    "talle": "42",
    "estado": "restaurado",
    "precio": 61600,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas urbanas gastadas seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zat-005",
    "nombre": "zapatillas clásicas blancas",
    "genero": "hombre",
    "categoria": "zapatilla",
    "talle": "43",
    "estado": "usado en buen estado",
    "precio": 64800,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas clásicas blancas seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zap-001",
    "nombre": "mocasines cuero marrón",
    "genero": "hombre",
    "categoria": "zapato",
    "talle": "39",
    "estado": "usado en excelente estado",
    "precio": 59000,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "mocasines cuero marrón seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zap-002",
    "nombre": "botines negros vintage",
    "genero": "hombre",
    "categoria": "zapato",
    "talle": "40",
    "estado": "usado en buen estado",
    "precio": 62200,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "botines negros vintage seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zap-003",
    "nombre": "zapatos oxford suela",
    "genero": "hombre",
    "categoria": "zapato",
    "talle": "41",
    "estado": "usado con detalles mínimos",
    "precio": 65400,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatos oxford suela seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zap-004",
    "nombre": "zapatos derby clásicos",
    "genero": "hombre",
    "categoria": "zapato",
    "talle": "42",
    "estado": "restaurado",
    "precio": 68600,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatos derby clásicos seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "hom-zap-005",
    "nombre": "náuticos cuero caramelo",
    "genero": "hombre",
    "categoria": "zapato",
    "talle": "43",
    "estado": "usado en buen estado",
    "precio": 71800,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "náuticos cuero caramelo seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-rem-001",
    "nombre": "remera baby tee floral",
    "genero": "mujer",
    "categoria": "remera",
    "talle": "s",
    "estado": "usado en excelente estado",
    "precio": 19500,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "remera baby tee floral seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-rem-002",
    "nombre": "remera básica vainilla",
    "genero": "mujer",
    "categoria": "remera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 22700,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "remera básica vainilla seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-rem-003",
    "nombre": "remera rayada roja",
    "genero": "mujer",
    "categoria": "remera",
    "talle": "l",
    "estado": "usado con detalles mínimos",
    "precio": 25900,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "remera rayada roja seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-rem-004",
    "nombre": "remera estampada pop",
    "genero": "mujer",
    "categoria": "remera",
    "talle": "xl",
    "estado": "restaurado",
    "precio": 29100,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "remera estampada pop seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-rem-005",
    "nombre": "remera oversized lavanda",
    "genero": "mujer",
    "categoria": "remera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 32300,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "remera oversized lavanda seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-swe-001",
    "nombre": "sweater mohair rosa",
    "genero": "mujer",
    "categoria": "sweater",
    "talle": "m",
    "estado": "usado en excelente estado",
    "precio": 39500,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "sweater mohair rosa seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-swe-002",
    "nombre": "cardigan perla vintage",
    "genero": "mujer",
    "categoria": "sweater",
    "talle": "l",
    "estado": "usado en buen estado",
    "precio": 42700,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "cardigan perla vintage seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-swe-003",
    "nombre": "sweater trenzado marfil",
    "genero": "mujer",
    "categoria": "sweater",
    "talle": "s",
    "estado": "usado con detalles mínimos",
    "precio": 45900,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "sweater trenzado marfil seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-swe-004",
    "nombre": "sweater cuello bote azul",
    "genero": "mujer",
    "categoria": "sweater",
    "talle": "m",
    "estado": "restaurado",
    "precio": 49100,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "sweater cuello bote azul seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-swe-005",
    "nombre": "sweater tejido terracota",
    "genero": "mujer",
    "categoria": "sweater",
    "talle": "xl",
    "estado": "usado en buen estado",
    "precio": 52300,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "sweater tejido terracota seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-cam-001",
    "nombre": "campera denim clara",
    "genero": "mujer",
    "categoria": "campera",
    "talle": "m",
    "estado": "usado en excelente estado",
    "precio": 70500,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera denim clara seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-cam-002",
    "nombre": "campera cuero cropped",
    "genero": "mujer",
    "categoria": "campera",
    "talle": "l",
    "estado": "usado en buen estado",
    "precio": 73700,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera cuero cropped seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-cam-003",
    "nombre": "campera bomber satinada",
    "genero": "mujer",
    "categoria": "campera",
    "talle": "s",
    "estado": "usado con detalles mínimos",
    "precio": 76900,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera bomber satinada seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-cam-004",
    "nombre": "tapado corto escocés",
    "genero": "mujer",
    "categoria": "campera",
    "talle": "xl",
    "estado": "restaurado",
    "precio": 80100,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "tapado corto escocés seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-cam-005",
    "nombre": "campera gabardina arena",
    "genero": "mujer",
    "categoria": "campera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 83300,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "campera gabardina arena seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-pan-001",
    "nombre": "jean mom vintage",
    "genero": "mujer",
    "categoria": "pantalon",
    "talle": "40",
    "estado": "usado en excelente estado",
    "precio": 47500,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "jean mom vintage seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-pan-002",
    "nombre": "pantalón sastre chocolate",
    "genero": "mujer",
    "categoria": "pantalon",
    "talle": "42",
    "estado": "usado en buen estado",
    "precio": 50700,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "pantalón sastre chocolate seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-pan-003",
    "nombre": "pantalón tiro alto crema",
    "genero": "mujer",
    "categoria": "pantalon",
    "talle": "44",
    "estado": "usado con detalles mínimos",
    "precio": 53900,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "pantalón tiro alto crema seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-pan-004",
    "nombre": "jean flare celeste",
    "genero": "mujer",
    "categoria": "pantalon",
    "talle": "38",
    "estado": "restaurado",
    "precio": 57100,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "jean flare celeste seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-pan-005",
    "nombre": "pantalón pana bordó",
    "genero": "mujer",
    "categoria": "pantalon",
    "talle": "46",
    "estado": "usado en buen estado",
    "precio": 60300,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "pantalón pana bordó seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zat-001",
    "nombre": "zapatillas lona marfil",
    "genero": "mujer",
    "categoria": "zapatilla",
    "talle": "39",
    "estado": "usado en excelente estado",
    "precio": 53500,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas lona marfil seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zat-002",
    "nombre": "zapatillas retro rosa",
    "genero": "mujer",
    "categoria": "zapatilla",
    "talle": "40",
    "estado": "usado en buen estado",
    "precio": 56700,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas retro rosa seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zat-003",
    "nombre": "zapatillas running pastel",
    "genero": "mujer",
    "categoria": "zapatilla",
    "talle": "41",
    "estado": "usado con detalles mínimos",
    "precio": 59900,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas running pastel seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zat-004",
    "nombre": "zapatillas urbanas crema",
    "genero": "mujer",
    "categoria": "zapatilla",
    "talle": "42",
    "estado": "restaurado",
    "precio": 63100,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas urbanas crema seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zat-005",
    "nombre": "zapatillas clásicas azul",
    "genero": "mujer",
    "categoria": "zapatilla",
    "talle": "43",
    "estado": "usado en buen estado",
    "precio": 66300,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatillas clásicas azul seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zap-001",
    "nombre": "mocasines charol negro",
    "genero": "mujer",
    "categoria": "zapato",
    "talle": "39",
    "estado": "usado en excelente estado",
    "precio": 60500,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "mocasines charol negro seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zap-002",
    "nombre": "botas urbanas cuero",
    "genero": "mujer",
    "categoria": "zapato",
    "talle": "40",
    "estado": "usado en buen estado",
    "precio": 63700,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "botas urbanas cuero seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zap-003",
    "nombre": "zapatos mary jane bordó",
    "genero": "mujer",
    "categoria": "zapato",
    "talle": "41",
    "estado": "usado con detalles mínimos",
    "precio": 66900,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatos mary jane bordó seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zap-004",
    "nombre": "zapatos oxford crema",
    "genero": "mujer",
    "categoria": "zapato",
    "talle": "42",
    "estado": "restaurado",
    "precio": 70100,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "zapatos oxford crema seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "muj-zap-005",
    "nombre": "botinetas gamuza miel",
    "genero": "mujer",
    "categoria": "zapato",
    "talle": "43",
    "estado": "usado en buen estado",
    "precio": 73300,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "botinetas gamuza miel seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": false,
    "disponible": true
  },
  {
    "idProducto": "out-rem-001",
    "nombre": "outlet remera college gris",
    "genero": "outlet",
    "categoria": "remera",
    "talle": "s",
    "estado": "usado en excelente estado",
    "precio": 14040,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet remera college gris seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-rem-002",
    "nombre": "outlet remera rayada verde",
    "genero": "outlet",
    "categoria": "remera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 16536,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet remera rayada verde seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-rem-003",
    "nombre": "outlet remera faded azul",
    "genero": "outlet",
    "categoria": "remera",
    "talle": "l",
    "estado": "usado con detalles mínimos",
    "precio": 19032,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet remera faded azul seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-rem-004",
    "nombre": "outlet remera gráfica retro",
    "genero": "outlet",
    "categoria": "remera",
    "talle": "xl",
    "estado": "restaurado",
    "precio": 21528,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet remera gráfica retro seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-rem-005",
    "nombre": "outlet remera básica arena",
    "genero": "outlet",
    "categoria": "remera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 24024,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet remera básica arena seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-swe-001",
    "nombre": "outlet sweater tejido mostaza",
    "genero": "outlet",
    "categoria": "sweater",
    "talle": "m",
    "estado": "usado en excelente estado",
    "precio": 29640,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet sweater tejido mostaza seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-swe-002",
    "nombre": "outlet cardigan crema",
    "genero": "outlet",
    "categoria": "sweater",
    "talle": "l",
    "estado": "usado en buen estado",
    "precio": 32136,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet cardigan crema seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-swe-003",
    "nombre": "outlet sweater lana gris",
    "genero": "outlet",
    "categoria": "sweater",
    "talle": "s",
    "estado": "usado con detalles mínimos",
    "precio": 34632,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet sweater lana gris seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-swe-004",
    "nombre": "outlet sweater cuello alto",
    "genero": "outlet",
    "categoria": "sweater",
    "talle": "m",
    "estado": "restaurado",
    "precio": 37128,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet sweater cuello alto seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-swe-005",
    "nombre": "outlet sweater trenzado oliva",
    "genero": "outlet",
    "categoria": "sweater",
    "talle": "xl",
    "estado": "usado en buen estado",
    "precio": 39624,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet sweater trenzado oliva seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-cam-001",
    "nombre": "outlet campera denim rota",
    "genero": "outlet",
    "categoria": "campera",
    "talle": "m",
    "estado": "usado en excelente estado",
    "precio": 53820,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet campera denim rota seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-cam-002",
    "nombre": "outlet campera bomber verde",
    "genero": "outlet",
    "categoria": "campera",
    "talle": "l",
    "estado": "usado en buen estado",
    "precio": 56316,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet campera bomber verde seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-cam-003",
    "nombre": "outlet campera cuero gastada",
    "genero": "outlet",
    "categoria": "campera",
    "talle": "s",
    "estado": "usado con detalles mínimos",
    "precio": 58812,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet campera cuero gastada seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-cam-004",
    "nombre": "outlet gabardina vintage",
    "genero": "outlet",
    "categoria": "campera",
    "talle": "xl",
    "estado": "restaurado",
    "precio": 61308,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet gabardina vintage seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-cam-005",
    "nombre": "outlet campera varsity roja",
    "genero": "outlet",
    "categoria": "campera",
    "talle": "m",
    "estado": "usado en buen estado",
    "precio": 63804,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet campera varsity roja seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-pan-001",
    "nombre": "outlet jean recto claro",
    "genero": "outlet",
    "categoria": "pantalon",
    "talle": "40",
    "estado": "usado en excelente estado",
    "precio": 35880,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet jean recto claro seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-pan-002",
    "nombre": "outlet pantalón pinzado negro",
    "genero": "outlet",
    "categoria": "pantalon",
    "talle": "42",
    "estado": "usado en buen estado",
    "precio": 38376,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet pantalón pinzado negro seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-pan-003",
    "nombre": "outlet cargo beige",
    "genero": "outlet",
    "categoria": "pantalon",
    "talle": "44",
    "estado": "usado con detalles mínimos",
    "precio": 40872,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet cargo beige seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-pan-004",
    "nombre": "outlet jean relaxed azul",
    "genero": "outlet",
    "categoria": "pantalon",
    "talle": "38",
    "estado": "restaurado",
    "precio": 43368,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet jean relaxed azul seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-pan-005",
    "nombre": "outlet pantalón pana verde",
    "genero": "outlet",
    "categoria": "pantalon",
    "talle": "46",
    "estado": "usado en buen estado",
    "precio": 45864,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet pantalón pana verde seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zat-001",
    "nombre": "outlet zapatillas lona beige",
    "genero": "outlet",
    "categoria": "zapatilla",
    "talle": "39",
    "estado": "usado en excelente estado",
    "precio": 40560,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet zapatillas lona beige seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zat-002",
    "nombre": "outlet zapatillas running retro",
    "genero": "outlet",
    "categoria": "zapatilla",
    "talle": "40",
    "estado": "usado en buen estado",
    "precio": 43056,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet zapatillas running retro seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zat-003",
    "nombre": "outlet zapatillas urbanas blancas",
    "genero": "outlet",
    "categoria": "zapatilla",
    "talle": "41",
    "estado": "usado con detalles mínimos",
    "precio": 45552,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet zapatillas urbanas blancas seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zat-004",
    "nombre": "outlet zapatillas clásicas negras",
    "genero": "outlet",
    "categoria": "zapatilla",
    "talle": "42",
    "estado": "restaurado",
    "precio": 48048,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet zapatillas clásicas negras seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zat-005",
    "nombre": "outlet zapatillas azul vintage",
    "genero": "outlet",
    "categoria": "zapatilla",
    "talle": "43",
    "estado": "usado en buen estado",
    "precio": 50544,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet zapatillas azul vintage seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zap-001",
    "nombre": "outlet mocasines marrón",
    "genero": "outlet",
    "categoria": "zapato",
    "talle": "39",
    "estado": "usado en excelente estado",
    "precio": 46020,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet mocasines marrón seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "retro club",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zap-002",
    "nombre": "outlet botas urbanas negras",
    "genero": "outlet",
    "categoria": "zapato",
    "talle": "40",
    "estado": "usado en buen estado",
    "precio": 48516,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet botas urbanas negras seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "archivo vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zap-003",
    "nombre": "outlet zapatos oxford cuero",
    "genero": "outlet",
    "categoria": "zapato",
    "talle": "41",
    "estado": "usado con detalles mínimos",
    "precio": 51012,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet zapatos oxford cuero seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "garage vintage",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zap-004",
    "nombre": "outlet derby clásico negro",
    "genero": "outlet",
    "categoria": "zapato",
    "talle": "42",
    "estado": "restaurado",
    "precio": 53508,
    "stock": 1,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet derby clásico negro seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "feria circular",
    "esOutlet": true,
    "disponible": true
  },
  {
    "idProducto": "out-zap-005",
    "nombre": "outlet botines cuero gastado",
    "genero": "outlet",
    "categoria": "zapato",
    "talle": "43",
    "estado": "usado en buen estado",
    "precio": 56004,
    "stock": 2,
    "imagen": "assets/product-placeholder.svg",
    "descripcion": "outlet botines cuero gastado seleccionada para griffin clothing, con estética vintage y disponibilidad simulada para la demo académica.",
    "vendedor": "griffin selection",
    "esOutlet": true,
    "disponible": true
  }
];
